### PR TITLE
Don't use mutable default argument.

### PR DESCRIPTION
**Pull request by bpkroth**
If this isn't respected, then additional_configs can be built up overtime when multiple optimizers are created in a single process.

This can occur when the use_default_config option is set True and/or when additional_configs are provided.

When different ConfigSpaces are provided this can result in an error due to mismatched defaults, for instance.

In other cases it can result in non-deterministic behavior due to the random ordering of the configs that get added (e.g., with different parallel pytest runs).

- [x] Cleanup other sources of this error as well elsewhere in the code.
- [x] Add pylint checks for this issue.

### CODE REVIEW

**Comment by helegraf** [comment]
Thanks for spotting and addressing this issue! We will discuss how we want to adapt the pre-commit hooks.

**Comment by helegraf** [comment]
Could you please add a line to the `CHANGELOG.md` mentioning the bugfix?

**Comment by bpkroth** [comment]
> Could you please add a line to the `CHANGELOG.md` mentioning the bugfix?

Hey, did that again.  Anything else?  Thanks!

**Comment by benjamc** [comment]
Closed by #1097

**Pull request closed without merging**
