### PR TITLE
Fixed the installation issue

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by mlindauer** [comment]
@KOLANICH Thank you for the PR.

@mfeurer could you please look into it since you know more about installation scripts than I do.

**Comment by mfeurer** [comment]
Thanks for the PR and pointing out this problem. 

While your proposed solution would fix the installation problem it removes the authors list from the setup (which I'm unhappy about). I'd suggest to add a file __authors__ which contains the authors list and can then be parsed by `ast.literal_eval()`. Let me know if you want to update your PR or pass this to us/me.

**Comment by mfeurer** [comment]
Fixes #469.

**Comment by KOLANICH** [comment]
>add a file authors which contains the authors list and can then be parsed by ast.literal_eval(). Let me know if you want to update your PR or pass this to us/me.

I suggest to
1 move all the metadata into setup.cfg (the info is automatically imported by setuptools, for examples how it may look like see any repo authored by me in my GH profile)
2 keep the list of authors there too. Or use an external file and use `file: `  to put it there (again see the examples in my repos).

**Comment by mlindauer** [comment]
@KEggensperger This was fixed in your PR (already merged into the dev). So, we can close this PR?

**Pull request closed without merging**
