### PR TITLE
MAINT init now shown alongside moduledocstring, fixed some aquisition…

### PR DESCRIPTION
**Pull request by shukon**
Docs now showing init as well as module docstring (issue/#265), also fixed some docstrings in aquisition.

```
cd doc
make html
```
shoud suffice.

### CODE REVIEW

**Comment by shukon** [comment]
@mfeurer aaah, I misunderstood the problem. Inherited members are now shown. Can you confirm this on your local build?

**Comment by mfeurer** [comment]
Great, I think it now looks as expected. I will go over the docstrings to make sure they're fine (wasn't part of your task I think) as soon as I find the time to do so.

**Comment by mfeurer** [comment]
I did a few changes to the docstrings in alphabetical manner until `initial_design`. Then I rebased it on master and will merge now to avoid merge conflicts in the upcoming Hackathon.

**Comment by mfeurer** [comment]
@KEggensperger @mlindauer not sure if there is time to do so during the Hackathon, but it would be great if someone could rework the modules from intensification onwards (mostly fixing grammar, making sure the signatures are correct and adding links).

**Pull request merged**
