### PR TITLE
feat: Option preventing SMAC setting up logging

### PR DESCRIPTION
**Pull request by eddiebergman**
Allow a user to disable SMAC from setting up its own custom logging by passing `logging_level=False`. This change is backwards compatible and does not change any existing behaviours.

Please see issue #948

### CODE REVIEW

**Review by alexandertornede — APPROVED** [review]
LGTM

**Comment by alexandertornede** [comment]
@eddiebergman Shouldn't this go to develop? Please also update the changelog :).

**Review by benjamc — APPROVED** [review]
Update changelog + merge into dev

**Comment by eddiebergman** [comment]
Done, I rebased ontop of `main` to also pull in the divergences from `development` before rebasing ontop of `development`.

**Comment by alexandertornede** [comment]
Ah, makes sense! Thanks! Feel free to merge :).

**Review by alexandertornede — COMMENTED** [review]
LGTM

**Pull request merged**
