### PR TITLE
Issue/#268 Switch to new pcs format

### PR DESCRIPTION
**Pull request by KEggensperger**
With this PR we would switch to the latest pcs format. I added ordinal hyperparameter values, but other than that I could not find anything that does not work using some quick checks and writing simple pcs files.

This PR can be merged as soon as the ConfigSpace is updated on pypi and we agree that it works for our optimization problems.

### CODE REVIEW

**Comment by mlindauer** [comment]
@mfeurer I hope there will be no issues. In theory, the new pcs should be a superset of the old pcs regarding the expressiveness.

**Comment by mlindauer** [comment]
As discussed in the ConfigSpace repo, I changed all iteration over configuration to use the get() function instead of []. 
I hope we can merge this soon.

**Comment by mfeurer** [comment]
I just updated the ConfigSpace on pypi to allow reading/writing of the new pcs format with Constants. Your latest issue regarding inconsistencies is not solved yet, though.

**Comment by mlindauer** [comment]
@mfeurer I still think it would be great if the inconsistency could be solved at some point. but for now, let's merge this.

**Pull request merged**
