### PR TITLE
Documentation changes reflecting #544

### PR DESCRIPTION
**Pull request by stheid**
I hope everything is correct, this is my first pullrequest :D

### CODE REVIEW

**Comment by gamer01** [comment]
see #544

**Comment by mlindauer** [comment]
@KEggensperger could you please also briefly look over the PR?

**Comment by mlindauer** [comment]
@mfeurer @KEggensperger could someone of you two please also look over this PR

**Comment by mfeurer** [comment]
Unfortunately, the changes make the examples fail. @gamer01 could you please have a look in why exactly the example fails with this change?

**Pull request merged**
