### PR TITLE
FIX #56, refactor execute ta classes

### LINKED ISSUE #56: support_memory_limit not initialized
```
Traceback (most recent call last):
  File "/home/lindauer/git/SMAC3/scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/home/lindauer/git/SMAC3/smac/smac_cli.py", line 47, in main_cli
    smbo.run(max_iters=args_.max_iterations)
  File "/home/lindauer/git/SMAC3/smac/smbo/smbo.py", line 282, in run
    self.incumbent = self.run_initial_design()
  File "/home/lindauer/git/SMAC3/smac/smbo/smbo.py", line 239, in run_initial_design
    instance_specific=self.scenario.instance_specific.get(rand_inst, "0"))
  File "/home/lindauer/git/SMAC3/smac/tae/execute_ta_run.py", line 103, in start
    if self._supports_memory_limit is True:
AttributeError: 'ExecuteTARunOld' object has no attribute '_supports_memory_limit'
```
The new feature with memory limit broke the command line target algorithm classes. 

The problem is that `_supports_memory_limit` is not inherited by its children.
The `super()` is wrongly used.
It should be something like:

```
        super().__init__(ta=ta,
                         stats=stats,
                         run_obj=run_obj)
```

We need to fix this asap since the current release cannot be used with the command line interface

### PR DESCRIPTION
**Pull request by mfeurer**

### CODE REVIEW

**Comment by KEggensperger** [comment]
approved

**Comment by mlindauer** [comment]
There was still an issue with the if clause for the raised exception on non-supported memory limit. Now, it is working again for me.

**Comment by mlindauer** [comment]
approved...
after my fix, katha needs to approve again ;-)

**Comment by mfeurer** [comment]
Can I also approve your fix?

**Comment by KEggensperger** [comment]
approve

**Pull request merged**
