### PR TITLE
FIX #50

### LINKED ISSUE #50: Variance prediction across Instances should not take instance hardness distribution into account
Right now, our variance prediction marginalized across instances (used for EI) also takes into account the instance hardness distribution (by using the law of total variance). However, as discussed with Stefan and Katha, this is actually wrong here. 
We only want to use the mean of the variance (without the variance of the means).

I will create a PR for this.

### PR DESCRIPTION
**Pull request by mlindauer**
FIX for #50

### CODE REVIEW

**Comment by mfeurer** [comment]
APPROVED

**Comment by mfeurer** [comment]
As mentioned in the related issue, I think this is the correct way of computing variances and this PR makes sense. We can merge this when all tests on travis work again.

**Comment by mlindauer** [comment]
ok, unit test should be fixed again

**Comment by mfeurer** [comment]
I now used the github approval feature. Not sure if we still need pullapprove?

**Comment by KEggensperger** [comment]
Yes, we do still need pullapprove if we want approvals to be mandatory. The github approval is optional for non protected branches, like our development branch.  See here: https://help.github.com/articles/enabling-required-reviews-for-pull-requests/.

Is there any other advantage of github approve over pullapprove? If not I would propose to continue using pullapprove.

**Comment by KEggensperger** [comment]
approved

**Comment by mlindauer** [comment]
ok, I will merge this PR and you can discuss the use of pullapprove offline, ok?

**Pull request merged**
