### PR TITLE
FIX #17/#26

### LINKED ISSUE #17: KeyError
Originally reported by: **Matthias Feurer (Bitbucket: [mfeurer](https://bitbucket.org/mfeurer), GitHub: [mfeurer](https://github.com/mfeurer))**

----------------------------------------

I got this error:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-10-a9f6024df581> in <module>()
     38 smbo = SMBO(scenario=scenario, rng=1, tae_runner=taf)
     39 Stats.scenario = scenario
---> 40 smbo.run(max_iters=100)
     41 
     42 print("Final Incumbent: %s" % (smbo.incumbent))

/home/feurerm/virtualenvs/ml2016/local/lib/python2.7/site-packages/smac/smbo/smbo.pyc in run(self, max_iters)
    291                 run_history=self.runhistory,
    292                 objective=self.objective,
--> 293                 time_bound=max(0.01, time_spend))
    294 
    295             # TODO: Write run history into database

/home/feurerm/virtualenvs/ml2016/local/lib/python2.7/site-packages/smac/smbo/intensification.pyc in intensify(self, challengers, incumbent, run_history, objective, time_bound)
    226                 chall_inst_seeds = set(map(lambda x: (
    227                     x.instance, x.seed), run_history.get_runs_for_config(challenger)))
--> 228                 chal_perf = objective(challenger, run_history, chall_inst_seeds)
    229                 run_history.update_cost(challenger, chal_perf)
    230 

/home/feurerm/virtualenvs/ml2016/local/lib/python2.7/site-packages/smac/smbo/objective.pyc in average_cost(config, run_history, instance_seed_pairs)
    116     float
    117     """
--> 118     return np.mean(_cost(config, run_history, instance_seed_pairs))
    119 
    120 def sum_cost(config, run_history, instance_seed_pairs=None):

/home/feurerm/virtualenvs/ml2016/local/lib/python2.7/site-packages/smac/smbo/objective.pyc in _cost(config, run_history, instance_seed_pairs)
     93     for i, r in instance_seed_pairs:
     94         k = run_history.RunKey(id_, i, r)
---> 95         costs.append(run_history.data[k].cost)
     96     return costs
     97 

KeyError: RunKey(config_id=36, instance_id='2', seed=931243971)
```
I'll try to reproduce this.

----------------------------------------
- Bitbucket: https://bitbucket.org/aadfreiburg/smac3/issue/17

### PR DESCRIPTION
**Pull request by mfeurer**
Supersedes #31 

Fixes #17 and #26 (together with the latest version of the config space).

### CODE REVIEW

**Comment by mfeurer** [comment]
@mlindauer @KEggensperger please review and comment on this. @mlindauer if you agree on this, can you please close #31?

**Comment by mlindauer** [comment]
Hi,

Thanks for the fix. It is working with my examples and the code should be fine.

However, I would like to propose a further change (because of efficiency and consistency).
The method Runhistory.get_runs_for_config() should get the `config_id` of `config` and compare the ids in the if-statement.
Comparison of int should be more efficient and we only need one dictionary access (instead of many in Line 111).  Furthermore, it is more consistent to use also here the `config_id` as we do it also in `objective._cost()`

Cheers,
Marius

**Comment by mfeurer** [comment]
Would it be okay to add this as an issue and solve in a separate PR?

**Comment by mlindauer** [comment]
> Would it be okay to add this as an issue and solve in a separate PR?

Yes. 
I thought it is very related to your fix and it reduces the overhead to create again another PR with an additional review phase.

**Comment by mlindauer** [comment]
Ok, I will submit a PR for #35, after this PR was merged.

There is no "approve" button in Github?

Cheers,
Marius

**Comment by mfeurer** [comment]
Correct, there is no "approve" button. We could adapt the scikit-learn policy of changing the PR names like this:

* [WIP] name: pull request is work in progress
* name: pull request is ready to be reviewed
* [MRG] name: pull request is approved by one reviewer
* [MRG+2] name: pull request is approved by two reviewers.

**Comment by KEggensperger** [comment]
approved

**Pull request merged**
