### PR TITLE
Compute the actual differences between the isb keys.

### LINKED ISSUE #956: Bug: get_incumbent_instance_seed_budget_key_differences does not correctly compute the differences.
#### Description
[`get_incumbent_instance_seed_budget_key_differences()`](https://github.com/automl/SMAC3/blob/731854e8effe72d76cb07636458e783143f32dc5/smac/intensifier/abstract_intensifier.py#L409) in `intensifier/abstract_intensifier.py` should "return the instances that are not part of the lowest intersection of instances for all incumbents.". This does not happen unfortunately. 

#### Steps/Code to Reproduce

Example code:
`incumbent_isb_keys = [[1, 2, 3], [1, 2], [1,2,3]]`
`incumbent_isb_keys = list(set.difference(*map(set, incumbent_isb_keys)))` 

#### Expected Results

`incumbent_isb_keys = [3]`

#### Actual Results

`incumbent_isb_keys = []`

#### Solution
Pull request will follow shortly after, but replacing the line with
`intersection_isb_keys = set.intersection(*map(set, incumbent_isb_keys))`
`union_isb_keys = set.union(*map(set, incumbent_isb_keys))`
`incumbent_isb_keys = list(union_isb_keys - intersection_isb_keys)`
computes the difference correctly.

### PR DESCRIPTION
**Pull request by jeroenrook**
Fixes #956 , by first computing the union and intersection of the incumbents and then taking the difference.

### CODE REVIEW

**Review by benjamc — APPROVED** [review]
Good spot!

**Comment by benjamc** [comment]
Can you update the changelog? Then I can merge

**Comment by jeroenrook** [comment]
Updated the changelog!

**Review by benjamc — APPROVED** [review]

**Comment by benjamc** [comment]
Thank you!

**Pull request merged**
