### PR TITLE
FIX #46, also fixes the following issues:

### LINKED ISSUE #46: Allow to return additional run information from a python function target algorithm
instead of returning an empty dictionary right now. How about:

    rval = obj(config)
    if isinstance(rval, tuple):
        value = rval[0]
        additional_run_info  rval[1]
    else:
        value = rval

### PR DESCRIPTION
**Pull request by mfeurer**
1. limit wallclock time instead of cpu time. I was not able to write
   a unit test which limits cpu time, and I don't see a reason why
   one would only want to limit cpu time
2. allow to enforce a memory limit
3. consider the algorithm run to have failed if the return value is
   None
4. add unittests

### CODE REVIEW

**Comment by mfeurer** [comment]
@mlindauer @KEggensperger what do you think?

Besides that, I'm confused where the conflict comes from.

**Comment by mlindauer** [comment]
Hi,

The memory limit will not work. 
After applying the PR for #40, we added the new function `start` in ExecuteTARun. The `start` function calls the `run` function of the heirs of ExecuteTARun (i.e., `start` wraps `run`). The `start` function is indeed important since it handles logging and entries in the stats. 
However, `start` does not have an argument for the memory limit and I'm also hesitant to add this argument in `start` since a memory limit is not supported by the other TA heirs.

Cheers,
Marius

**Comment by mfeurer** [comment]
Then I should maybe remove it from this PR and add it to all TAs?

**Comment by mlindauer** [comment]
How do you want to add it all TAs? Unfortunately, the memlimit of the pynisher is not working for the other TAs.

**Comment by mfeurer** [comment]
And the others don't assume that the runsolver is installed, right?

**Comment by mlindauer** [comment]
yes

**Comment by mfeurer** [comment]
Okay, I found the source of the merge conflict. I forgot to pull the latest changes from the development branch. I did a rebase of my two commits.

**Comment by mfeurer** [comment]
@mlindauer okay, I made the relevant updates. Tests are working again after @KEggensperger updated the travis-ci configuration file.

**Comment by KEggensperger** [comment]
Approved

**Pull request merged**
