### PR TITLE
Development

### PR DESCRIPTION
**Pull request by mfeurer**

### CODE REVIEW

**Comment by mlindauer** [comment]
Running the dev branch (in particular with the changes of yesterday afternoon), I get an error:

```
Traceback (most recent call last):
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/smac_cli.py", line 83, in main_cli
    optimizer.optimize()
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/facade/smac_facade.py", line 308, in optimize
    incumbent = self.solver.run()
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/smbo/smbo.py", line 134, in run
    time_bound=max(0.01, time_spend))
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/intensification/intensification.py", line 151, in intensify
    aggregate_func=aggregate_func)
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/intensification/intensification.py", line 325, in _race_challenger
    aggregate_func=aggregate_func)
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/intensification/intensification.py", line 421, in _compare_configs
    incumbent, run_history, chall_runs)
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/smbo/objective.py", line 117, in average_cost
    return np.mean(_cost(config, run_history, instance_seed_pairs))
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/smbo/objective.py", line 94, in _cost
    costs.append(run_history.data[k].cost)
KeyError: RunKey(config_id=40, instance_id='instances/mip/data/RCW2/map1404-s147847-b06-h40-n5.lp', seed=0)
```

I would like to first investigate this problem, before approving the merge.

**Comment by mlindauer** [comment]
btw: using the master branch of the ConfigSpace, I get the following error:

```
Traceback (most recent call last):
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/smac_cli.py", line 83, in main_cli
    optimizer.optimize()
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/facade/smac_facade.py", line 308, in optimize
    incumbent = self.solver.run()
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/smbo/smbo.py", line 121, in run
    challengers = self.choose_next(X, Y)
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/smbo/smbo.py", line 214, in choose_next
    configs_previous_runs_sorted[:num_configs_local_search])))
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/smbo/smbo.py", line 282, in _get_next_by_local_search
    configuration, acq_val = self.acq_optimizer.maximize(start_point)
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-mip/configurators/smac3/smac/smbo/local_search.py", line 95, in maximize
    self.rng.shuffle(all_neighbors)
  File "mtrand.pyx", line 4648, in mtrand.RandomState.shuffle (numpy/random/mtrand/mtrand.c:30072)
TypeError: object of type 'generator' has no len()
```

**Comment by mfeurer** [comment]
The second error is easy to explain. Instead of a list of neighbors, you get an iterator which has no length. Therefore, you'd have to remove the shuffling and then it should work.

**Comment by mlindauer** [comment]
the first error is maybe because of an added debug statement (which is not in the dev branch). I will first rerun it to verify that everything is fine now before I approve it. Ok?

**Comment by mfeurer** [comment]
Sure. I don't think the fix I added is the root problem, because it only assures that the runhistory is consistent. Maybe it brought one other bug to the surface :). I'll check back in one or two hours.

**Comment by mlindauer** [comment]
the filesystem on nemo is broken again... so,  I cannot look in my files anymore and my benchmarks are probably also trash now...

**Comment by mfeurer** [comment]
Is it somehow possible that challenger got to line 323 without having a single run and thus wasn't added to the runhistory? The only example I can think of would be that it didn't go through the loop in lines 295-321.

**Comment by mlindauer** [comment]
the above error has not re-occurred again after I removed my debug statement. Therefore, I assume that my debug statement had caused the exception.
Hence, I will approve your merge, but I still believe that there is a critical bug in the code. At least, the release should not make it worse than before.

**Pull request merged**
